/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagingRouteImport } from './routes/staging'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LogincopyRouteImport } from './routes/login copy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as BursaDataRouteImport } from './routes/bursa-data'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const StagingRoute = StagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LogincopyRoute = LogincopyRouteImport.update({
  id: '/login copy',
  path: '/login copy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const BursaDataRoute = BursaDataRouteImport.update({
  id: '/bursa-data',
  path: '/bursa-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/login': typeof LoginRoute
  '/login copy': typeof LogincopyRoute
  '/security': typeof SecurityRoute
  '/staging': typeof StagingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/login': typeof LoginRoute
  '/login copy': typeof LogincopyRoute
  '/security': typeof SecurityRoute
  '/staging': typeof StagingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/login': typeof LoginRoute
  '/login copy': typeof LogincopyRoute
  '/security': typeof SecurityRoute
  '/staging': typeof StagingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/bursa-data'
    | '/deployment'
    | '/login'
    | '/login copy'
    | '/security'
    | '/staging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/bursa-data'
    | '/deployment'
    | '/login'
    | '/login copy'
    | '/security'
    | '/staging'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/bursa-data'
    | '/deployment'
    | '/login'
    | '/login copy'
    | '/security'
    | '/staging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BursaDataRoute: typeof BursaDataRoute
  DeploymentRoute: typeof DeploymentRoute
  LoginRoute: typeof LoginRoute
  LogincopyRoute: typeof LogincopyRoute
  SecurityRoute: typeof SecurityRoute
  StagingRoute: typeof StagingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staging': {
      id: '/staging'
      path: '/staging'
      fullPath: '/staging'
      preLoaderRoute: typeof StagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login copy': {
      id: '/login copy'
      path: '/login copy'
      fullPath: '/login copy'
      preLoaderRoute: typeof LogincopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursa-data': {
      id: '/bursa-data'
      path: '/bursa-data'
      fullPath: '/bursa-data'
      preLoaderRoute: typeof BursaDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BursaDataRoute: BursaDataRoute,
  DeploymentRoute: DeploymentRoute,
  LoginRoute: LoginRoute,
  LogincopyRoute: LogincopyRoute,
  SecurityRoute: SecurityRoute,
  StagingRoute: StagingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
