/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagingRouteImport } from './routes/staging'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as BursaDataRouteImport } from './routes/bursa-data'
import { Route as IndexRouteImport } from './routes/index'

const StagingRoute = StagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const BursaDataRoute = BursaDataRouteImport.update({
  id: '/bursa-data',
  path: '/bursa-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/staging': typeof StagingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/staging': typeof StagingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bursa-data': typeof BursaDataRoute
  '/deployment': typeof DeploymentRoute
  '/staging': typeof StagingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bursa-data' | '/deployment' | '/staging'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bursa-data' | '/deployment' | '/staging'
  id: '__root__' | '/' | '/bursa-data' | '/deployment' | '/staging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BursaDataRoute: typeof BursaDataRoute
  DeploymentRoute: typeof DeploymentRoute
  StagingRoute: typeof StagingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staging': {
      id: '/staging'
      path: '/staging'
      fullPath: '/staging'
      preLoaderRoute: typeof StagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursa-data': {
      id: '/bursa-data'
      path: '/bursa-data'
      fullPath: '/bursa-data'
      preLoaderRoute: typeof BursaDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BursaDataRoute: BursaDataRoute,
  DeploymentRoute: DeploymentRoute,
  StagingRoute: StagingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
